app:
  message: Hi from properties!
  port: 8080
  mockoon: http://localhost:3004/api/v1
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/issue-tracker
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://user-profile-manager-keycloak.staging.intesys.it/realms/codylab


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: it.intesys.academy.controller.rest
logging:
  level:
    root: info
    org.springframework.security: debug
