app:
  message: Hi from properties!
  mockoon: http://localhost:3004/api/v1
  port: 8080
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/Users/Zeno/Documents/intesys/databaseCustomerPortal/dataBase
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
