app:
  message: Hi from properties!
  port: 8080
  mockoon: http://localhost:3004/api/v1
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/Users/Alessia/Intesys-Java/CodyLab-FirstSpringProject
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: it.intesys.academy.controller.rest
