app:
  message: Hi from properties!
  port: 8080
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/issue-tracker
    username: sa
    password: password
