app:
  message: Hi from properties!
  port: 8080
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/Users/biond/OneDrive/Desktop/database/default
    username: sa
    password: password
