openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080/openapi
tags:
  - name: Projects
    description: Projects API
paths:
  /projects/{username}:
    get:
      tags:
        - Projects
      operationId: getProjectsForUsername
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Projects'

components:
  schemas:
    Projects:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
      example: {
        "id": 1,
        "name": "Project 1",
        "description": "Description 1"}
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
      example: {
        "id": 1,
        "name": "Project 1",
        "description": "Description 1"}