openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081/openapi
    description: Generated server url
tags:
  - name: Project
    description: Project API
  - name: Issue
    description: Issue API
paths:
  /projects/{projectId}:
    get:
      tags:
        - Project
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Project'
    put:
      tags:
        - Project
      operationId: updateProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BadParametersError'
                  - $ref: '#/components/schemas/BadUsernameError'

    delete:
      tags:
        - Project
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Project
      operationId: patchProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Project'
  /issues/{issueId}:
    get:
      tags:
        - Issue
      operationId: getIssue
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Issue'
    put:
      tags:
        - Issue
      operationId: updateIssue
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Issue'
    delete:
      tags:
        - Issue
      operationId: deleteIssue
      parameters:
        - name: issueId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /projects:
    get:
      tags:
        - Project
      operationId: getProjects
      parameters:
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - Project
      operationId: createProject
      parameters:
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Project'
  /issues:
    get:
      tags:
        - Issue
      operationId: getIssues
      parameters:
        - name: projectId
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      tags:
        - Issue
      operationId: createIssue
      parameters:
        - name: X-User-Name
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Issue'
components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int32
        text:
          type: string
        author:
          type: string
        issueId:
          type: integer
          format: int32
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int32
        projectId:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        author:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
      example: {
                 "id": 1,
                 "name": "Project 1",
                 "description": "Description 1"}
    BadParametersError:
      type: object
      properties:
        errorType:
          type: string
        timestamp:
          type: string
          format: date-time
    BadUsernameError:
      type: object
      properties:
        errorType:
          type: string
        timestamp:
          type: string
          format: date-time
